name: Create Tagged Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP archive
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'export_calibre_books_plugin.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig README.md'

      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: export_calibre_books_plugin.zip
          name: Release ${{ github.ref_name }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
